kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: group-sync-operator
  labels:
    kubernetes.io/metadata.name: group-sync-operator
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ''
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
